(() => {
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
  const field = (label, value) => `<dt>${esc(label)}</dt><dd>${esc(value)}</dd>`;
  async function api(path) { const response = await fetch(path, { credentials: 'same-origin' }); const body = await response.json(); if (!response.ok) throw new Error(body.reason || '读取失败'); return body; }
  async function refresh() {
    $('status').textContent = '读取中'; $('error').hidden = true;
    try {
      const [model, inbox, inbound, outbox, actions] = await Promise.all([api('/ui/connection'), api('/ui/inbox'), api('/ui/inbound-tasks'), api('/ui/outbox'), api('/ui/human-actions').catch(() => ({ requests: [] }))]);
      $('status').textContent = model.status === 'connected' ? '已连接' : model.status;
      $('summary').textContent = `${model.network_id} · ${model.peers.length} 个参与节点`;
      $('local').innerHTML = field('节点', model.local_node.node_id) + field('名称', model.local_node.display_name) + field('Agent', `${model.local_node.agent_kind} / ${model.local_node.agent_version}`);
      $('network').innerHTML = field('网络', model.network_id) + field('状态', model.status) + field('副作用', model.side_effects_executed ? '是' : '否');
      $('peers').innerHTML = model.peers.length ? model.peers.map((peer) => `<article class="peer"><div><strong>${esc(peer.node_id)}</strong><small>${esc(peer.endpoint)} · ${esc(peer.next_action)}</small></div><span class="peer-status">${esc(peer.status)}</span></article>`).join('') : '<article class="peer"><small>当前没有参与节点。</small></article>';
      $('inbox-status').textContent = `${inbox.messages.length} 条消息`;
      $('messages').innerHTML = inbox.messages.length ? inbox.messages.map((message) => `<article class="message"><div><strong>${esc(message.notification_kind)}</strong><small>${esc(message.from_node_id)} → ${esc(message.target_node_id)} · ${esc(message.task_id)}</small></div><span class="peer-status">${esc(message.delivery_state)}</span></article>`).join('') : '<article class="message"><small>当前没有消息。</small></article>';
      $('inbound-status').textContent = `${inbound.tasks.length} 条任务`;
      window.__opnInboundTasks = inbound.tasks;
      $('inbound-tasks').innerHTML = inbound.tasks.length ? inbound.tasks.map((task) => { const pending = task.status === 'pending-human-approval'; return `<article class="message"><div><strong>${esc(task.envelope.task_id || task.inbound_id)}</strong><small>${esc(task.envelope.from_node_id)} → ${esc(task.envelope.target_node_id)} · ${esc(task.envelope.message_id)}</small><small>Artifact ${esc((task.envelope.artifact_refs || []).map((ref) => ref.artifact_id).join(', ') || 'none')}</small>${pending ? `<label>Agent <input data-inbound-agent="${esc(task.inbound_id)}" value="${esc(task.envelope.target_node_id)}"></label><label>备注 <input data-inbound-note="${esc(task.inbound_id)}" placeholder="Human review note"></label><div><button data-inbound-decision="approved" data-inbound-id="${esc(task.inbound_id)}">批准</button><button data-inbound-decision="rejected" data-inbound-id="${esc(task.inbound_id)}">拒绝</button></div>` : ''}</div><span class="peer-status">${esc(task.status)}</span></article>`; }).join('') : '<article class="message"><small>当前没有待人工批准的入站任务。</small></article>';
      $('outbox-status').textContent = `${outbox.messages.length} 条消息`;
      $('outbox').innerHTML = outbox.messages.length ? outbox.messages.map((message) => `<article class="message"><div><strong>${esc(message.notification_kind)}</strong><small>${esc(message.from_node_id)} → ${esc(message.target_node_id)} · ${esc(message.task_id)}</small></div><span class="peer-status">已发送</span></article>`).join('') : '<article class="message"><small>当前没有已发送消息。</small></article>';
      $('actions-status').textContent = `${actions.requests.length} 条 action`;
      $('human-actions').innerHTML = actions.requests.length ? actions.requests.map((action) => `<article class="message"><div><strong>${esc(action.action_type)}</strong><small>${esc(action.requester_node_id)} · ${esc(action.reason)}</small><small>Evidence ${esc(action.evidence_refs?.length || 0)} · ${esc(action.request_id)}</small></div><span class="peer-status">${esc(action.status)}</span></article>`).join('') : '<article class="message"><small>当前没有 Human action。</small></article>';
    } catch (error) { $('status').textContent = '读取受阻'; $('error').textContent = error.message; $('error').hidden = false; }
  }
  $('inbound-tasks').addEventListener('click', async (event) => { const button = event.target.closest('button[data-inbound-decision]'); if (!button) return; const inboundId = button.dataset.inboundId; const task = inboundId ? stateInboundTask(inboundId) : null; const note = document.querySelector(`[data-inbound-note="${CSS.escape(inboundId || '')}"]`)?.value.trim(); const agent = document.querySelector(`[data-inbound-agent="${CSS.escape(inboundId || '')}"]`)?.value.trim(); if (!task || !note || (button.dataset.inboundDecision === 'approved' && !agent)) { $('error').hidden = false; $('error').textContent = 'Human note and selected Agent are required.'; return; } button.disabled = true; try { await fetch(`/ui/inbound-tasks/${encodeURIComponent(inboundId)}/decision`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ envelope_digest: task.envelope.envelope_digest, decision: button.dataset.inboundDecision, human_id: 'local-human', human_note: note, ...(agent ? { selected_agent_id: agent } : {}) }) }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.reason || 'decision-failed'); }); await refresh(); } catch (error) { $('error').hidden = false; $('error').textContent = error.message; button.disabled = false; } });
  function stateInboundTask(inboundId) { return window.__opnInboundTasks?.find((task) => task.inbound_id === inboundId) || null; }
  $('refresh').addEventListener('click', refresh); refresh();
})();
