# zj-loop-generated: true
# zj-loop-template-id: gitlab-ci/zj-loop-root
# zj-loop-template-version: 1
# zj-loop-template-hash: generated-by-zj-loop-init

stages:
  - zj-loop

include:
  - local: "zj-loop/gitlab-ci/zj-loop-smoke.yml"
