import assert from 'node:assert/strict';
import test from 'node:test';

import {
  buildIssueTriageTransitionIssueFixRequestBody,
  buildRecommendedTriageTransitionFixture,
  executeGitLabIssueTriageTransition,
  runIssueTriageTransitionRunner,
} from '../dist/index.js';

const ROUTE = {
  route_id: 'issue-triage-transition', consumer: 'issue-triage-transition', consumer_kind: 'triage-action-consumer', enabled: true,
  request_kind: 'triage-transition-confirmation', execution_mode: 'request-only', side_effect_level: 'request',
  completion_forms: ['triage-transition-confirmed', 'issue-fix-request-created', 'triage-action-skipped', 'escalation-issue'],
  guards: { trusted_automation_confirmation_allowed: true, trusted_automation_states: ['ready-for-agent'], trusted_automation_authorities: ['trusted-workflow'], side_effects_allowed: 'request-carrier-only' },
};

function request() {
  return buildRecommendedTriageTransitionFixture({
    source: { tracker: 'gitlab', repo: 'mlive-dev/ai-studio', issue: 160, issue_url: 'https://git.bilibili.co/mlive-dev/ai-studio/-/issues/160', scan_window: 'open-issues:last-24h' },
    dedupe_key: 'issue-backlog-triage:mlive-dev/ai-studio:160:ready-for-agent:test',
  });
}

test('GitLab transition refuses cross-project requests before any Notes API call', async () => {
  let calls = 0;
  const result = await executeGitLabIssueTriageTransition({
    projectPath: 'mlive-dev/ai-studio', issueIid: 160, token: 'token', apiBaseUrl: 'https://git.bilibili.co/api/v4', route: ROUTE,
    request: { ...request(), source: { ...request().source, repo: 'other/project' } }, fetchImpl: async () => { calls += 1; throw new Error('unexpected'); },
  });
  assert.equal(result.status, 'blocked');
  assert.equal(result.reason, 'request-source-mismatch');
  assert.equal(calls, 0);
});

test('GitLab transition creates a source Issue Fix Request note with low-cost evidence', async () => {
  const calls = [];
  const result = await executeGitLabIssueTriageTransition({
    projectPath: 'mlive-dev/ai-studio', issueIid: 160, token: 'token', apiBaseUrl: 'https://git.bilibili.co/api/v4', route: ROUTE,
    request: request(), actorPermission: 'maintainer', command: request().confirm_command, confirmationPhrase: 'CONFIRM_TRIAGE_TRANSITION',
    fetchImpl: async (url, init = {}) => {
      calls.push({ url: String(url), init });
      if (init.method === 'POST') return { ok: true, status: 201, async json() { return { id: 88, web_url: 'https://git.bilibili.co/mlive-dev/ai-studio/-/issues/160#note_88', body: JSON.parse(init.body).body }; } };
      return { ok: true, status: 200, async json() { return []; } };
    },
  });
  assert.equal(result.status, 'completed', JSON.stringify(result));
  assert.equal(result.outcome, 'created');
  assert.equal(result.note.id, '88');
  assert.equal(result.audit.auth_source, 'GITLAB_TOKEN');
  assert.equal(calls.filter((call) => call.init.method === 'POST').length, 1);
  assert.equal(calls[1].init.body.includes('> *This was generated by AI during triage.*'), true);
});

test('GitLab transition returns duplicate without posting a second note', async () => {
  const base = runIssueTriageTransitionRunner({ route: ROUTE, request: request(), actorPermission: 'maintainer', command: request().confirm_command, confirmationPhrase: 'CONFIRM_TRIAGE_TRANSITION' });
  const body = buildIssueTriageTransitionIssueFixRequestBody({ issueFixRequest: base.confirmed_transition.issue_fix_request, triageComment: base.confirmed_transition.triage_comment });
  let postCount = 0;
  const result = await executeGitLabIssueTriageTransition({
    projectPath: 'mlive-dev/ai-studio', issueIid: 160, token: 'token', apiBaseUrl: 'https://git.bilibili.co/api/v4', route: ROUTE,
    request: request(), actorPermission: 'maintainer', command: request().confirm_command, confirmationPhrase: 'CONFIRM_TRIAGE_TRANSITION',
    fetchImpl: async (url, init = {}) => {
      if (init.method === 'POST') postCount += 1;
      return { ok: true, status: 200, async json() { return [{ id: 88, body }]; } };
    },
  });
  assert.equal(result.status, 'completed');
  assert.equal(result.outcome, 'duplicate');
  assert.equal(postCount, 0);
});

test('trusted GitLab transition requires schedule context and explicit enablement', async () => {
  const result = await executeGitLabIssueTriageTransition({
    projectPath: 'mlive-dev/ai-studio', issueIid: 160, token: 'token', apiBaseUrl: 'https://git.bilibili.co/api/v4', route: ROUTE,
    request: request(), confirmationMode: 'trusted-automation', confirmationAuthority: 'trusted-workflow', pipelineSource: 'web', trustedAutomationEnabled: 'enabled',
  });
  assert.equal(result.status, 'blocked');
  assert.equal(result.reason, 'trusted-automation-context-invalid');
});

test('trusted GitLab transition recovers an uncertain write by reading the marker once', async () => {
  const base = runIssueTriageTransitionRunner({ route: ROUTE, request: request(), confirmationMode: 'trusted-automation', confirmationAuthority: 'trusted-workflow' });
  const body = buildIssueTriageTransitionIssueFixRequestBody({ issueFixRequest: base.confirmed_transition.issue_fix_request, triageComment: base.confirmed_transition.triage_comment });
  let reads = 0;
  const result = await executeGitLabIssueTriageTransition({
    projectPath: 'mlive-dev/ai-studio', issueIid: 160, token: 'token', apiBaseUrl: 'https://git.bilibili.co/api/v4', route: ROUTE,
    request: request(), confirmationMode: 'trusted-automation', confirmationAuthority: 'trusted-workflow', pipelineSource: 'schedule', trustedAutomationEnabled: 'enabled',
    fetchImpl: async (url, init = {}) => {
      if (init.method === 'POST') throw new Error('write-timeout');
      reads += 1;
      return reads === 1 ? { ok: true, status: 200, async json() { return []; } } : { ok: true, status: 200, async json() { return [{ id: 91, body }]; } };
    },
  });
  assert.equal(result.status, 'completed');
  assert.equal(result.outcome, 'recovered-duplicate');
});

test('GitLab transition replays a response mismatch and preserves the created note evidence', async () => {
  const base = runIssueTriageTransitionRunner({ route: ROUTE, request: request(), confirmationMode: 'trusted-automation', confirmationAuthority: 'trusted-workflow' });
  const body = buildIssueTriageTransitionIssueFixRequestBody({ issueFixRequest: base.confirmed_transition.issue_fix_request, triageComment: base.confirmed_transition.triage_comment });
  let reads = 0;
  const result = await executeGitLabIssueTriageTransition({
    projectPath: 'mlive-dev/ai-studio', issueIid: 160, token: 'token', apiBaseUrl: 'https://git.bilibili.co/api/v4', route: ROUTE,
    request: request(), confirmationMode: 'trusted-automation', confirmationAuthority: 'trusted-workflow', pipelineSource: 'schedule', trustedAutomationEnabled: 'enabled',
    fetchImpl: async (url, init = {}) => {
      if (init.method === 'POST') return { ok: true, status: 201, async json() { return { id: 19639888, body: 'normalized-by-gitlab' }; } };
      reads += 1;
      return reads === 1 ? { ok: true, status: 200, async json() { return []; } } : { ok: true, status: 200, async json() { return [{ id: 19639888, body }]; } };
    },
  });
  assert.equal(result.status, 'completed', JSON.stringify(result));
  assert.equal(result.outcome, 'recovered-duplicate');
  assert.equal(result.note.id, '19639888');
  assert.equal(result.note.url, 'https://git.bilibili.co/mlive-dev/ai-studio/-/issues/160#note_19639888');
});
