import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';

import {
  buildLiveRunnerEvidence,
  validateLiveRunnerEvidence,
} from './live-runner-contract.js';
import { buildIssueFixRequestComment } from './issue-fix-request-contract.js';
import { RouteStatus } from './route.js';

export const RECOMMENDED_TRIAGE_TRANSITION_SCHEMA = 'zj-loop.recommended_triage_transition.v1';
export const CONFIRMED_TRIAGE_TRANSITION_SCHEMA = 'zj-loop.confirmed_triage_transition.v1';
export const TRIAGE_AI_DISCLAIMER = '> *This was generated by AI during triage.*';
export const CONFIRM_TRIAGE_TRANSITION_COMMAND = '/zj-loop confirm-triage-transition';

const ROUTE_ID = 'issue-triage-transition';
const RUNNER_ID = 'issue-triage-transition';
const CONSUMER_KIND = 'triage-action-consumer';
const ALLOWED_STATES = new Set(['needs-info', 'ready-for-agent', 'ready-for-human', 'wontfix']);
const ALLOWED_CATEGORIES = new Set(['bug', 'enhancement']);
const ALLOWED_PERMISSIONS = new Set(['maintainer', 'admin', 'write', 'collaborator']);

export async function readRecommendedTriageTransition(path: string) {
  return JSON.parse(await readFile(path, 'utf8'));
}

export function buildRecommendedTriageTransitionFixture(overrides: Record<string, unknown> = {}) {
  const request: any = {
    schema: RECOMMENDED_TRIAGE_TRANSITION_SCHEMA,
    request_id: 'triage-transition-agent-ready',
    source: {
      tracker: 'github',
      repo: 'jununfly/ZAgenticLoop',
      issue: 126,
      issue_url: 'https://github.com/jununfly/ZAgenticLoop/issues/126',
      scan_window: 'open-issues:last-24h',
    },
    route_decision: {
      route_id: 'issue-backlog-triage',
      status: 'recommended',
      decision_id: 'rd_issue_triage_fixture',
    },
    category_role: 'bug',
    recommended_state: 'ready-for-agent',
    confidence: 'high',
    reason: 'Issue is bounded enough for an AFK agent after confirmed transition.',
    risk_flags: [],
    brief_draft: {
      kind: 'agent-brief',
      body: 'Agent brief draft for issue-126.',
    },
    dedupe_key: 'issue-backlog-triage:jununfly/ZAgenticLoop:126:ready-for-agent:fixture',
    confirm_command: 'noop',
    required_actor_permission: 'maintainer-or-collaborator',
    side_effects_if_confirmed: {
      set_tracker_state: true,
      write_triage_comment: true,
      create_issue_fix_request: 'ready-for-agent-only',
    },
    stale_after: '2026-07-14T00:00:00.000Z',
    ...overrides,
  };
  request.confirm_command = `${CONFIRM_TRIAGE_TRANSITION_COMMAND} ${request.request_id}`;
  return request;
}

export function runIssueTriageTransitionRunner(input: {
  route: RouteStatus;
  request?: any;
  actorPermission?: string;
  command?: string;
  confirmationPhrase?: string;
  createdAt?: string;
  live?: boolean;
}) {
  const request = buildRecommendedTriageTransitionFixture(input.request ?? {});
  const decision = decideTransition({
    route: input.route,
    request,
    actorPermission: input.actorPermission ?? 'maintainer',
    command: input.command ?? request.confirm_command,
    confirmationPhrase: input.confirmationPhrase ?? 'CONFIRM_TRIAGE_TRANSITION',
    live: input.live === true,
  });
  const confirmedTransition = buildConfirmedTransition({
    request,
    decision,
    createdAt: input.createdAt ?? '2026-07-09T00:00:00Z',
  });
  const evidence = buildEvidence({
    request,
    decision,
    confirmedTransition,
    route: input.route,
    live: input.live === true,
    createdAt: input.createdAt ?? '2026-07-09T00:00:00Z',
  });
  const validation = validateLiveRunnerEvidence(evidence);

  return {
    kind: 'zj-loop.issue-triage-transition-runner-result',
    route_id: ROUTE_ID,
    dry_run: input.live !== true,
    decision,
    confirmed_transition: confirmedTransition,
    evidence,
    validation,
    run_id: stableHash(JSON.stringify({ decision, confirmedTransition, evidence })),
  };
}

export function buildIssueTriageTransitionIssueFixRequestTitle(issueFixRequest: any) {
  const repo = issueFixRequest?.source_signal?.repo ?? 'unknown-repo';
  const issue = issueFixRequest?.source_signal?.issue ?? 'unknown-issue';
  const requestId = issueFixRequest?.request_id ?? 'unknown-request';
  return `[Issue Fix Request] issue-triage-transition: ${repo}#${issue} ${requestId}`;
}

export function buildIssueTriageTransitionIssueFixRequestBody(input: {
  issueFixRequest: any;
  triageComment?: string | null;
}) {
  const request = input.issueFixRequest;
  const comment = buildIssueFixRequestComment(request).trim();
  return [
    `# Issue Fix Request: ${request.requested_consumer.consumer_id}`,
    '',
    comment,
    '',
    '## Human-readable summary',
    '',
    `- Source issue: ${request.source_signal.url || `${request.source_signal.repo}#${request.source_signal.issue}`}`,
    `- Source route: \`${request.source_signal.source}\``,
    `- Requested consumer: \`${request.requested_consumer.consumer_id}\``,
    `- Dedupe key: \`${request.dedupe_key}\``,
    '',
    '## Triage brief',
    '',
    input.triageComment ?? request.acceptance_criteria.join('\n'),
    '',
    'The Fix Consumer must open a verifier-backed Fix PR or append failed/escalation evidence.',
    '',
  ].join('\n');
}

function decideTransition(input: {
  route?: RouteStatus;
  request: any;
  actorPermission: string;
  command: string;
  confirmationPhrase: string;
  live: boolean;
}) {
  const routeValid = input.route?.enabled === true
    && input.route?.route_id === ROUTE_ID
    && input.route?.consumer_kind === CONSUMER_KIND
    && (input.route?.execution_mode === 'dry-run' || input.route?.execution_mode === 'request-only')
    && input.route?.request_kind === 'triage-transition-confirmation';
  const requestValid = validateRecommendedTransition(input.request);
  if (!input.route) return decision('rejected', 'route-not-found');
  if (!routeValid) return decision('rejected', 'route-contract-invalid');
  if (input.live) return decision('rejected', 'live-side-effects-not-enabled');
  if (!requestValid.ok) return decision('rejected', `request-invalid:${requestValid.errors[0]}`);
  if (!ALLOWED_PERMISSIONS.has(input.actorPermission)) return decision('rejected', 'actor-not-maintainer-or-collaborator');
  if (input.command !== input.request.confirm_command) return decision('rejected', 'confirm-command-mismatch');
  if (input.confirmationPhrase !== 'CONFIRM_TRIAGE_TRANSITION') return decision('rejected', 'fixed-confirmation-phrase-required');
  if (input.request.recommended_state === 'wontfix') return decision('escalated', 'wontfix-requires-human-review');
  if (input.request.risk_flags?.length > 0 && input.request.recommended_state !== 'ready-for-human') {
    return decision('escalated', 'risk-flags-require-human-review');
  }
  return decision('confirmed', 'triage-transition-confirmed');
}

function validateRecommendedTransition(request: any) {
  const errors: string[] = [];
  if (request?.schema !== RECOMMENDED_TRIAGE_TRANSITION_SCHEMA) errors.push('schema');
  if (!request?.request_id) errors.push('request_id');
  if (!request?.source?.repo || !request?.source?.issue) errors.push('source');
  if (request?.route_decision?.route_id !== 'issue-backlog-triage') errors.push('route_decision.route_id');
  if (!ALLOWED_CATEGORIES.has(request?.category_role)) errors.push('category_role');
  if (!ALLOWED_STATES.has(request?.recommended_state)) errors.push('recommended_state');
  if (!request?.brief_draft?.kind || !request?.brief_draft?.body) errors.push('brief_draft');
  if (!request?.dedupe_key) errors.push('dedupe_key');
  if (request?.confirm_command !== `${CONFIRM_TRIAGE_TRANSITION_COMMAND} ${request?.request_id}`) {
    errors.push('confirm_command');
  }
  return { ok: errors.length === 0, errors };
}

function buildConfirmedTransition(input: { request: any; decision: { status: string; reason: string }; createdAt: string }) {
  const request = input.request;
  const status = input.decision.status === 'confirmed' ? 'confirmed' : input.decision.status;
  return {
    schema: CONFIRMED_TRIAGE_TRANSITION_SCHEMA,
    request_id: request.request_id,
    status,
    reason: input.decision.reason,
    created_at: input.createdAt,
    source: request.source,
    category_role: request.category_role,
    confirmed_state: request.recommended_state,
    tracker_operations: operationsFor(request, input.decision),
    triage_comment: commentFor(request, input.decision),
    issue_fix_request: issueFixRequestFor(request, input.decision, input.createdAt),
  };
}

function operationsFor(request: any, decisionResult: { status: string }) {
  if (decisionResult.status !== 'confirmed') return [];
  return [
    { kind: 'set-category-role', role: request.category_role },
    { kind: 'set-state-role', role: request.recommended_state },
  ];
}

function commentFor(request: any, decisionResult: { status: string }) {
  if (decisionResult.status !== 'confirmed') return null;
  return [
    TRIAGE_AI_DISCLAIMER,
    '',
    `## ${titleForState(request.recommended_state)}`,
    '',
    request.brief_draft.body,
  ].join('\n');
}

function issueFixRequestFor(request: any, decisionResult: { status: string }, createdAt: string) {
  if (decisionResult.status !== 'confirmed' || request.recommended_state !== 'ready-for-agent') return null;
  return {
    schema: 'zj-loop.issue_fix_request.v1',
    request_id: `ifr_triage_${stableHash(request.dedupe_key)}`,
    status: 'requested',
    created_at: createdAt,
    source_signal: {
      source: 'issue-backlog-triage',
      repo: request.source.repo,
      issue: request.source.issue,
      url: request.source.issue_url,
    },
    route_decision: {
      route_id: 'issue-backlog-triage',
      request_kind: 'issue-fix-request',
      target_consumer: 'roadmap-sliced-development',
      dedupe_key: `issue-fix-request:${request.source.repo}:${request.source.issue}:ready-for-agent`,
    },
    dedupe_key: `issue-fix-request:${request.source.repo}:${request.source.issue}:ready-for-agent`,
    requested_consumer: { consumer_id: 'roadmap-sliced-development' },
    fix_scope: { scopes: ['issue-fix'], areas: ['triage-confirmed'] },
    acceptance_criteria: [request.brief_draft.body],
    verification_gate: {
      verifiers: ['route-replay', 'zj-triage-brief'],
      commands: ['git diff --check'],
    },
    failure_policy: { retry: 'new_request_only' },
    lifecycle: [{ status: 'requested', at: createdAt, actor: 'issue-triage-transition' }],
  };
}

function buildEvidence(input: {
  request: any;
  decision: { status: string; reason: string };
  confirmedTransition: any;
  route?: RouteStatus;
  live: boolean;
  createdAt: string;
}) {
  return buildLiveRunnerEvidence({
    runner_id: RUNNER_ID,
    route_id: ROUTE_ID,
    consumer_kind: CONSUMER_KIND,
    execution_mode: input.route?.execution_mode ?? (input.live ? 'live' : 'dry-run'),
    completion_form: completionFormFor(input.request, input.decision),
    status: input.decision.status === 'confirmed' ? 'completed' : input.decision.status === 'escalated' ? 'escalated' : 'skipped',
    dedupe_key: input.request.dedupe_key,
    created_at: input.createdAt,
    source: {
      kind: 'recommended-triage-transition',
      id: input.request.request_id,
      url: input.request.source?.issue_url,
    },
    verifier_evidence: [
      { kind: 'route-table', route_id: ROUTE_ID, status: 'matched' },
      { kind: 'permission', required: 'maintainer-or-collaborator', status: input.decision.status },
      { kind: 'fixed-confirmation-command', command: input.request.confirm_command, status: input.decision.status },
      { kind: 'zj-triage-role-contract', state: input.request.recommended_state, status: input.decision.status },
    ],
    side_effects: {
      executed: false,
      level: input.request.recommended_state === 'ready-for-agent' ? 'request' : 'label',
      actions: input.decision.status === 'confirmed' ? input.confirmedTransition.tracker_operations : [],
      triage_comment_planned: input.confirmedTransition.triage_comment !== null,
      issue_fix_request_planned: input.confirmedTransition.issue_fix_request !== null,
    },
  });
}

function completionFormFor(request: any, decisionResult: { status: string }) {
  if (decisionResult.status === 'escalated') return 'escalation-issue';
  if (decisionResult.status !== 'confirmed') return 'triage-action-skipped';
  return request.recommended_state === 'ready-for-agent' ? 'issue-fix-request-created' : 'triage-transition-confirmed';
}

function titleForState(state: string) {
  if (state === 'ready-for-agent') return 'Agent Brief';
  if (state === 'ready-for-human') return 'Human Handoff';
  return 'Triage Notes';
}

function decision(status: string, reason: string) {
  return { status, reason };
}

function stableHash(value: string) {
  return createHash('sha256').update(String(value)).digest('hex').slice(0, 12);
}
